import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Home Page",
    description: "Generated by create next app",
  };

const LandingLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main className="bg-zinc-100 h-screen dark:bg-zinc-900 overflow-auto">
      <div className="mx-auto max-w-screen-xl h-full w-full">{children}</div>
    </main>
  );
};

export default LandingLayout;
